[package]
name = "print_blocks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compiler_tools = { path = "../compiler_tools" }
serde_json = "1.0"
